AllCops:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/EachWithObject:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

Documentation:
  Enabled: false
