require 'ox'
require 'virtus'
require 'aasm'
require 'logger'

require_relative 'fb2/version'
require_relative 'fb2/type'
require_relative 'fb2/text'
require_relative 'fb2/stylesheet'
require_relative 'fb2/genre'
require_relative 'fb2/author'
require_relative 'fb2/image'
require_relative 'fb2/coverpage'
require_relative 'fb2/lang'
require_relative 'fb2/date'
require_relative 'fb2/sequence'
require_relative 'fb2/binary'
require_relative 'fb2/title'
require_relative 'fb2/epigraph'
require_relative 'fb2/body'
require_relative 'fb2/cite'
require_relative 'fb2/anchor'
require_relative 'fb2/text_author'
require_relative 'fb2/empty_line'
require_relative 'fb2/paragraph'
require_relative 'fb2/strong'
require_relative 'fb2/emphasis'
require_relative 'fb2/table'
require_relative 'fb2/verse'
require_relative 'fb2/poem'
require_relative 'fb2/stanza'
require_relative 'fb2/sequence'
require_relative 'fb2/style'
require_relative 'fb2/annotation'
require_relative 'fb2/section'
require_relative 'fb2/title_info'
require_relative 'fb2/custom_info'
require_relative 'fb2/document_info'
require_relative 'fb2/publish_info'
require_relative 'fb2/custom_info'
require_relative 'fb2/publish_info'
require_relative 'fb2/description'
require_relative 'fb2/parser'
require_relative 'fb2/book'

module Fb2
  # Your code goes here...
end
