require 'ox'
require 'virtus'
require 'aasm'
require 'logger'

require 'fb2/version'
require 'fb2/type'
require 'fb2/text'
require 'fb2/stylesheet'
require 'fb2/genre'
require 'fb2/author'
require 'fb2/image'
require 'fb2/coverpage'
require 'fb2/lang'
require 'fb2/date'
require 'fb2/sequence'
require 'fb2/binary'
require 'fb2/title'
require 'fb2/epigraph'
require 'fb2/body'
require 'fb2/cite'
require 'fb2/anchor'
require 'fb2/text_author'
require 'fb2/empty_line'
require 'fb2/paragraph'
require 'fb2/table'
require 'fb2/verse'
require 'fb2/poem'
require 'fb2/stanza'
require 'fb2/sequence'
require 'fb2/style'
require 'fb2/annotation'
require 'fb2/section'
require 'fb2/title_info'
require 'fb2/custom_info'
require 'fb2/document_info'
require 'fb2/publish_info'
require 'fb2/custom_info'
require 'fb2/publish_info'
require 'fb2/description'
require 'fb2/parser'
require 'fb2/book'

module Fb2
  # Your code goes here...
end
